#include "foo.h"
#include <exception>


int testfoo2(int argc, char * argv [] )
{
	foo f;
	
	//throw new std::exception();
	return 0;
}

